version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_STRAPI_URL=https://tududone.com/api
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    networks:
      - tududone_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  strapi:
    image: strapi/strapi:latest
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./my-blog-backend:/srv/app
      - strapi-data:/srv/app/.tmp
    ports:
      - "1337:1337"
    networks:
      - tududone_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1337/admin"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tududone_network:
    driver: bridge

volumes:
  strapi-data:
    driver: local

# Removemos o serviço nginx pois você já tem um nginx rodando 