version: '3'

services:
  web:
    container_name: tududone-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://tududone.com
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  strapi-data:
    driver: local

# Removemos o serviço nginx pois você já tem um nginx rodando 